version: "3.5"
services:
  web:
    build: .
    tty: true
    ports:
      - "3000:3000"
      - "5005:5005"
    env_file: .env
    volumes:
      - .:/galaxy
    command:
      ["./startgalaxy.sh",]